### ISSUE TITLE
Express-wrapper throws out middleware data from the request unless included in request codec

### ISSUE THREAD

**Issue by jonball4** [BitGo/api-ts#134]
In the current beta version, if we define route middleware via `express-wrapper` as such:

```
const exampleMiddleware = (apiName: string, method: 'get' | 'post' | 'put' | 'delete') => (req, res, next) => {
  req.apiName = apiName;
  req.method = method;
  next();
}

const createRouteHandler = <A, B>(
  apiName: string,
  method: 'get' | 'post' | 'put' | 'delete',
  handler: (_: A) => B,
) => ({
    middleware: [exampleMiddleware(apiName, method)],
    handler,
  })

export const v1ExampleRoute = httpRoute({
  path: 'my/example/path',
  method: 'GET',
  request: httpRequest({ parameter: t.string }),
  response: {
    200: t.type({ result: t.string }),
  },
});

export const v1ExampleSpec = apiSpec({
  ['v1.example.route']: {
    get: v1ExampleRoute
  },
});

const app = createServer(v1ExampleSpec, (expressApp) => (
  {
    ['v1.example.route']: {
      get: createRouteHandler('v1.example.route', 'get', handleExampleRequest),
    }
));
```

The `express-wrapper` uses the `httpRoute.request` codec to decode the express request and only passes the decoded values.  Anything else the middleware up til that request handler might have added to the request will be thrown out, unless the request codec includes the values added by the middleware.

https://github.com/BitGo/api-ts/blob/7dc00a4500104ff0b78b9f81bfcb68037dfe5a12/packages/express-wrapper/src/request.ts#L49

I think this warrants the need for a separate _middleware codec_ defined at the express server configuration level, to process the request w.r.t. the server level middleware in use.   Additionally, route-specific middleware warrants the need for route-specific middleware codecs as well.

**Comment by jonball4** [comment]
separately, we ought to be able to add middleware that runs after our request handler as well.  Currently we can only add middleware that runs before our request via `app.use` or adding middleware via the `RouteHandler`.

**Comment by ericcrosson-bitgo** [comment]
I'm trying to understand the problem, the lede is buried

Is the issue that middleware-added values (values that the middleware adds to the HTTP request) leave the service-developer with two options: 

1. the middleware-added values aren't described by the httpRoute codec, and thus dropped from the decoded request, or
2. the middleware-added values are described by the httpRoute codec, but there's no way to distinguish "values the client needs to provide" vs "values the middleware needs to provide?"

and neither is satisfactory?

> separately, we ought to be able to add middleware that runs after our request handler as well. Currently we can only add middleware that runs before our request via app.use or adding middleware via the RouteHandler.

Please punt this to a separate issue.

**Comment by jonball4** [comment]
> I'm trying to understand the problem, the lede is buried
> 
> Is the issue that middleware-added values (values that the middleware adds to the HTTP request) leave the service-developer with two options:
> 
> 1. the middleware-added values aren't described by the httpRoute codec, and thus dropped from the decoded request, or
> 2. the middleware-added values are described by the httpRoute codec, but there's no way to distinguish "values the client needs to provide" vs "values the middleware needs to provide"
> 
> and neither is satisfactory?
> 
> > separately, we ought to be able to add middleware that runs after our request handler as well. Currently we can only add middleware that runs before our request via app.use or adding middleware via the RouteHandler.
> 
> Please punt this to a separate issue.

punted the other comment to another issue. 

You hit the nail on the head.  If we want middleware to be able to pass values to our request handler, then we should have a way to differentiate between request parameters and parameters passed from middleware so we don't communicate the wrong contract with the api consumer.

**Comment by bitgopatmcl** [comment]
Yeah, this is sorely needed along with the middleware-after-request functionality. I'm currently working on something that can hopefully address these use cases alongside a few other things like route aliases and priority.
