### ISSUE TITLE
Define middleware to run after the request.

### ISSUE THREAD

**Issue by jonball4** [BitGo/api-ts#135]
We ought to be able to add middleware that runs after our request handler as well.  Currently we can only add middleware that runs before our request via `app.use` or adding middleware via the `RouteHandler`:

https://github.com/BitGo/api-ts/blob/7dc00a4500104ff0b78b9f81bfcb68037dfe5a12/packages/express-wrapper/src/index.ts#L56

Perhaps `beforeMiddleware` and `afterMiddleware` instead of just `middleware` in the `RouteHandler` definition.

**Comment by bitgopatmcl** [comment]
:+1: currently working a route where this is needed as well
