### ISSUE TITLE
Incompatibility between @api-ts/Response@beta and @api-ts/io-ts-http@beta

### ISSUE THREAD

**Issue by jonball4** [BitGo/api-ts#136]
https://github.com/BitGo/api-ts/blob/7dc00a4500104ff0b78b9f81bfcb68037dfe5a12/packages/response/src/index.ts#L12-L26

VS.

https://github.com/BitGo/api-ts/blob/7dc00a4500104ff0b78b9f81bfcb68037dfe5a12/packages/io-ts-http/src/httpResponse.ts#L3-L5

**Comment by bitgopatmcl** [comment]
I think this is technically resolved by [this](https://github.com/BitGo/api-ts/blob/beta/packages/io-ts-http/src/httpResponse.ts#L3-L5) but could be improved still
