### ISSUE TITLE
using PathReporter for showing decoding errors leads to thrown errors when using bigint

### ISSUE THREAD

**Issue by jonball4** [BitGo/api-ts#138]
https://github.com/BitGo/api-ts/blob/2c1e3900d30a9fa5f1d273fcf8b16933044aa091/packages/express-wrapper/src/request.ts#L52-L55

https://github.com/gcanti/io-ts/blob/920b21ea32e82b328cd14ff4b28da72ae60db505/src/PathReporter.ts#L8-L29

Since PathReporter uses JSON.stringify, which does not have handling for `bigint` by default, this causes an error to get thrown. 
 The result is that the request never gets a response and times out.
 
Suggesting we pull in our internal `validationErrors` routine from schema-lib, or our own version of the PathReporter.

**Comment by ericcrosson-bitgo** [comment]
> The result is that the request never gets a response and times out.

Yikes, we'll fix this. Thanks for the report!

Can you point me to the codec with a bigint? I'd like to see more about the input that causes this behavior

**Comment by jonball4** [comment]
sure!  Here it is:

https://github.com/BitGo/bitgo-microservices/blob/056251f23a001d0cf9549f49efc1a4b7380034c6/packages/bitgo-network/src/controllers/v1/allocation/response.ts#L5-L20

**Comment by bitgopatmcl** [comment]
Fixed in #267

**Comment by jonball4** [comment]
> Fixed in #267

almost..  PathReport will

**Comment by jonball4** [comment]
I suppose this is not an api-ts issue anymore.
