### ISSUE TITLE
can't use optional with query\params\body props when exactOptionalPropertyTypes = true

### ISSUE THREAD

**Issue by adrian-gierakowski** [BitGo/api-ts#272]
To reproduce:

make the following changes: https://github.com/rhinofi/api-ts/commit/fc7d71aa4ac34f58abb0a992c0549947cf80d67a

compiler will complain [here](https://github.com/rhinofi/api-ts/blob/fc7d71aa4ac34f58abb0a992c0549947cf80d67a/packages/superagent-wrapper/test/request.test.ts#L22) with following error:

```
/home/adrian/api-ts/packages/superagent-wrapper/test/request.test.ts:
   22:3   error   Type 'Type<{ foo?: string | undefined; id: number; bar: number; }, { query: { foo?: string | undefined; }; params: { id: string; }; body: { bar: number; }; }, unknown>' is not assignable to type 'HttpRequestCodec<any>'. ​typescript:2322
                    Types of property 'encode' are incompatible.
                      Type 'Encode<{ foo?: string | undefined; id: number; bar: number; }, { query: { foo?: string | undefined; }; params: { id: string; }; body: { bar: number; }; }>' is not assignable to type 'Encode<any, { query: { [x: string]: string | string[]; }; params: { [x: string]: string; }; } & { headers?: { [x: string]: string; } | undefined; body?: Json | undefined; }>'.
                        Type '{ query: { foo?: string | undefined; }; params: { id: string; }; body: { bar: number; }; }' is not assignable to type '{ query: { [x: string]: string | string[]; }; params: { [x: string]: string; }; } & { headers?: { [x: string]: string; } | undefined; body?: Json | undefined; }'.
```

for reference:
https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes
https://www.typescriptlang.org/tsconfig#strictNullChecks

**Comment by adrian-gierakowski** [comment]
[this](https://github.com/rhinofi/api-ts/commit/9847c48da18fdfa225033f4c894f658ae422197b) fixes the error, but I'm not sure if it  could have any undesired effects

additional fixes would be required for `params`, `body` and possibly `headers`

**Comment by bitgopatmcl** [comment]
Thanks for the bug report! As far as I can see, your fix would work, but it would be nice if we could keep the `GenericHttpRequest` type as simple as possible. I've opened #274 as a possible alternative solution that also enables `optionalized` to take advantage of the benefits of `exactOptionalPropertyTypes`. Please take a look and let me know if it works for your use case.

**Comment by adrian-gierakowski** [comment]
@bitgopatmcl thanks, this seems to work! Any chance for a release? 

btw. just a bit of feedback: it's a bit confusing that query, params and body are plain objects while responses are codecs, particularly in the context of `optional`, since in case of responses wrapping a prop with `optional` is not enough to allow it to omitted (need to use [`t.intersection` with `t.partial`](https://github.com/rhinofi/api-ts/commit/fc17206cf076ff0439a2fa1a25b019be8090d118)).

**Comment by ericcrosson-bitgo** [comment]
@adrian-gierakowski This has been published as @api-ts/io-ts-http v2.0.0 https://www.npmjs.com/package/@api-ts/io-ts-http?activeTab=versions

**Comment by adrian-gierakowski** [comment]
Oh, nice! I was looking at releases on GitHub and didn’t see it there :)  thanks!

**Comment by ericcrosson-bitgo** [comment]
I agree, something is wonky with our releases and the bot that comments on issues/PRs with the release version! We'll take a look so this information is presented more clearly in the future

**Comment by adrian-gierakowski** [comment]
Btw is there a changelog somewhere? Given major version bump it would be good to know if there any breaking changes

**Comment by ericcrosson-bitgo** [comment]
Thanks for the feedback! There's supposed to be, on the GitHub Release that didn't publish :sweat_smile: I'll see if I can create one manually until we can automate it's creation.

Since we're releasing on every commit to master, the PR @bitgopatmcl made to address this issue is the only change in io-ts-http v2.0.0

**Comment by adrian-gierakowski** [comment]
Sounds good! Thanks for the great work 👍

**Comment by ericcrosson-bitgo** [comment]
:bow: Thank you for guiding us in these early stages of the project!

> just a bit of feedback: it's a bit confusing that query, params and body are plain objects while responses are codecs

This is something we've heard several times, but I'll let @bitgopatmcl speak to any plans moving forward here.

I agree that it's a little unintuitive to expect `t.Props` to be passed in the request, but to require the user to pass a full codec for the response. The motivation behind the shape of the response is that we didn't want to constrain users to only returning full JSON objects. This way, we support returning numbers, strings, arrays, etc.

> particularly in the context of optional, since in case of responses wrapping a prop with optional is not enough to allow it to omitted (need to use [t.intersection with t.partial](https://github.com/rhinofi/api-ts/commit/fc17206cf076ff0439a2fa1a25b019be8090d118))

This is because `optional` only works when paired with `optionalize`! https://github.com/BitGo/api-ts/blob/master/packages/io-ts-http/docs/combinators.md#optional

So for example, if you were to write:

```typescript
const PostTestRoute = h.httpRoute({
  path: '/test/{id}',
  method: 'POST',
  request: h.httpRequest({
    query: {
      foo: h.optional(t.string),
    },
    params: {
      id: NumberFromString,
    },
    body: {
      bar: t.number,
    },
  }),
  response: {
    200: optionalize({
        id: t.number,
        bar: t.number,
        baz: t.boolean,
        foo: optional(t.string),
      }),
    401: t.type({
      message: t.string,
    }),
  },
});
```

you should see the behavior you expect.

**Comment by ericcrosson-bitgo** [comment]
I'm going to close the issue now as the original matter has been resolved, but that's not any signal to stop the discussion here :smiley:
