### ISSUE TITLE
Base path is lost when replacing path params

### ISSUE THREAD

**Issue by nicob21** [BitGo/api-ts#337]
When path params get replaces, we loose any base path that was set in the base url.

https://github.com/BitGo/api-ts/blob/master/packages/superagent-wrapper/src/request.ts#L79-L90

For example, if the base is `http://localhost/foo` and the route path is `/bar`
The url pathname contains `/foo`  at the beginning and after replacing the params in `/foo` the `/bar` part is lost.

That means that if all our endpoints have a common base param we can pass it in the base URL and we need to add it to every route.

Could we just concatenate the result of `substitutePathParams` to `url.pathname` instead of replacing it?

**Comment by adrian-gierakowski** [comment]
Thanks!
