### ISSUE TITLE
@api-ts/express-wrapper should have @api-ts/typed-express-router as dep not devDep

### ISSUE THREAD

**Issue by adrian-gierakowski** [BitGo/api-ts#486]
`@api-ts/typed-express-router` is here:

https://github.com/BitGo/api-ts/blob/a9b498c75ae00b5de4b5adab8b696395bcd3889e/packages/express-wrapper/src/index.ts#L9

while listed only as dev dep:

https://github.com/BitGo/api-ts/blob/a9b498c75ae00b5de4b5adab8b696395bcd3889e/packages/express-wrapper/package.json#L25-L27

this leads to errors when using strict package managers (like [yarn berry](https://github.com/yarnpkg/berry)) which don't leak dependencies between packages

**Comment by ericcrosson-bitgo** [comment]
Good catch! Thank you for the detailed report

**Comment by adrian-gierakowski** [comment]
Thanks for the quick fix!
