### ISSUE TITLE
Conflicting path param templates between ApiSpec expected by express-wrapper vs superagent-wrapper

### ISSUE THREAD

**Issue by jonball4** [BitGo/api-ts#53]
`express-wrapper` (and `express`) expects path params denoted as `api/v1/someapi/:param/someendpoint`:

https://github.com/BitGo/api-ts/blob/5467fb41f32ada3b50f1976580305f9a6765d221/packages/express-wrapper/src/index.ts#L144

Whereas the `superagent-wrapper` expects paths with params denoted as `api/v1/someapi/{param}/someendpoint`.

https://github.com/BitGo/api-ts/blob/822eebdf28a38b64f6a19e30f53726229d814397/packages/superagent-wrapper/src/request.ts#L185

This creates the inability to satisfy both requirements / send path params through superagent-wrapper while using io-ts-http and express-wrapper.

Example in test: https://github.com/BitGo/api-ts/blob/822eebdf28a38b64f6a19e30f53726229d814397/packages/superagent-wrapper/test/request.test.ts#L14 VS. https://github.com/BitGo/api-ts/blob/822eebdf28a38b64f6a19e30f53726229d814397/packages/superagent-wrapper/test/request.test.ts#L60

**Comment by ericcrosson-bitgo** [comment]
Closed by #54
